app <- ShinyDriver$new("..")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(show = TRUE)
app$snapshot()
app$setInputs(tab = "tabPanel(\"Test\", \"Test page\")")
app$setInputs(select = TRUE)
app$setInputs(menuName = "More")
app$snapshot()
app$setInputs(go = "click")
app$setInputs(navbarPage = "Test")
app$snapshot()
app$setInputs(tab = "navbarMenu(\"Dropdown\",               tabPanel(\"Drop1\", \"Drop1 page\"),               tabPanel(\"Drop2\", \"Drop2 page\"),               \"------\",               \"Header\",               tabPanel(\"Drop3\", \"Drop3 page\")             )")
app$setInputs(menuName = "")
app$setInputs(select = FALSE)
app$setInputs(action = "prepend")
app$setInputs(go = "click")
app$snapshot()
app$setInputs(navbarPage = "Drop2")
app$snapshot()
app$setInputs(action = "hide")
app$setInputs(target = "Dropdown")
app$setInputs(go = "click")
app$setInputs(navbarPage = "Main")
app$setInputs(navbarPage = "About")
app$setInputs(target = "About")
app$snapshot()
app$setInputs(go = "click")
app$setInputs(navbarPage = "Main")
app$snapshot()
app$setInputs(action = "show")
app$setInputs(target = "Dropdown")
app$setInputs(select = TRUE)
app$setInputs(go = "click")
app$setInputs(target = "About")
app$setInputs(go = "click")
app$setInputs(navbarPage = "About")
app$setInputs(action = "remove")
app$setInputs(target = "Si")
app$setInputs(target = "Simple")
app$setInputs(navbarPage = "Simple")
app$snapshot()
app$setInputs(go = "click")
app$setInputs(navbarPage = "Drop1")
app$snapshot()
