app <- ShinyDriver$new("..", seed = 123)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(n = 90)
app$snapshot()
app$setInputs(dist = "unif")
app$snapshot()
app$setInputs(tabs = "Summary")
app$snapshot()
app$setInputs(tabs = "Table")
app$snapshot()
app$setInputs(tabs = "Plot")
app$setInputs(dist = "exp")
app$snapshot()
