app <- ShinyDriver$new("..")
app$snapshotInit("mytests")

app$snapshot()
app$setInputs(add = "click")
app$setInputs(`slider-1` = 5)
app$setInputs(`slider-1` = 8)
app$snapshot()
app$setInputs(add = "click")
app$setInputs(`slider-2` = 5)
app$setInputs(`slider-2` = 2)
app$snapshot()
app$setInputs(add = "click")
app$setInputs(`slider-3` = 5)
app$snapshot()
