app <- ShinyDriver$new("..")
app$snapshotInit("mytests")

app$snapshot()
app$setInputs(add = "click")
app$setInputs(`slider-1` = 5, wait_=FALSE, values_=FALSE)
app$setInputs(`slider-1` = 8, wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(add = "click")
app$setInputs(`slider-2` = 5, wait_=FALSE, values_=FALSE)
app$setInputs(`slider-2` = 2, wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(add = "click")
app$setInputs(`slider-3` = 5, wait_=FALSE, values_=FALSE)
app$snapshot()
