app <- ShinyDriver$new("..")
app$snapshotInit("mytest")

app$setInputs(add = "click")
Sys.sleep(0.25)
app$setInputs(`slider-1` = 5)
app$setInputs(`slider-1` = 7)
app$snapshot()
app$setInputs(add = "click")
Sys.sleep(0.25)
app$setInputs(`slider-2` = 5)
app$setInputs(`slider-2` = 10)
app$snapshot()
app$setInputs(add = "click")
Sys.sleep(0.25)
app$setInputs(`slider-3` = 5)
app$snapshot()
